### ISSUE TITLE
New usb-c dongles not updated

### ISSUE THREAD

**Issue by maburdett** [franton/Set-DNS-info#1]
My new macbooks (dongles) are not being set by this script. It look like these adapters are identified as LAN rather than Ethernet.

**Comment by franton** [comment]
Can you post a screenshot of your network preference pane with the device attached?

**Comment by maburdett** [comment]
Richard, I haven't had a chance to get a hold of these devices to get
a screenshot
of your network preference but, I do have an extension attribute, "Active
Network interface" that grab the dongle name.

Active Network interface: USB 10/100/1000 LAN en8
Active Network interface: Belkin USB-C LAN en6

the EA I'm using is;

#!/bin/bash
ref=$(/usr/bin/sw_vers -productVersion | awk '{print substr($1,4,2)}')
case $ref in
[0-4] )
ntwkset="/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Support/networksetup
-listnetworkserviceorder"
        ;;
     *) ntwkset="networksetup -listnetworkserviceorder"
        ;;
esac

ifconfigoutput='
BEGIN            { print_it = 0 }
/status: active/ { print_it = 1 }
/^($|[^\t])/     { if(print_it) print buffer; buffer = $0; print_it = 0 }
/^\t/            { buffer = buffer "\n" $0 }
END              { if(print_it) print buffer }
'

ntwkint=($(ifconfig -u | awk "$ifconfigoutput" | awk '/flags/{print
substr($1,1,3)}'))
/bin/echo -n $"<result>"
for x in "${ntwkint[@]}"
do
echo `$ntwkset | grep "$x" | sed -e 's/[)(]//g;s/,//g;s/.*Port:
//g;s/Device:\ //g'`
done
echo "</result>"


-+mab
Michael A. Burdett
michael.a.burdett@gmail.com
cell 425.345.8595

**Comment by franton** [comment]
I don’t have a USB-C MacBook or dongle. I can’t easily work on this I’m afraid without that info.

**Comment by redshirtdave** [comment]
I have a generic USB-C Ethernet adapter called 'USB 10/100/1000 LAN' and the Belkin one. Modified the networksetup grep using `networksetup -listallnetworkservices | grep -E '(Ethernet|LAN)'`. Works fine to capture all previous interfaces and the new ones in my limited testing. Tested on two iMacs and a MBP USB-C model, macOS 10.12 and 10.13

**Comment by franton** [comment]
Ok so the way this script works, is that you specify a name and the script processes all forms of it that it can find. That means you simply have to set up a new policy using LAN instead of Ethernet. Technically speaking it's not a script fault.
